name: Docker Image CI/CD to GHCR

on:
  # push:
  #   branches: [ "master-main" ]
  workflow_dispatch:

env:
  # The image name for your project
  IMAGE_NAME: BiharDatamart 
  # Hardcoded Organization Name
  ORG_NAME: hemanth-beehyv

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Necessary to push to GitHub Container Registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # GITHUB_TOKEN has default 'write' access to the container registry
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Extract Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          # Using the hardcoded ORG_NAME instead of ${{ github.repository_owner }}
          images: ghcr.io/${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: build/bihardata/Dockerfile
          context: . # Searches for Dockerfile in the root of the repository
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
